### PR TITLE
Fix wrong import file names

### PR DESCRIPTION
**Pull request by BennyAlex**

### CODE REVIEW

**Comment by wojtekmaj** [comment]
They are correct. You missed the warning:

https://github.com/wojtekmaj/react-pdf#before-you-continue

**Comment by BennyAlex** [comment]
not sure what you want me to tell, since the readme should show the config for the latest version in my opinion, and also the link to v6 is not working
https://github.com/wojtekmaj/react-pdf/blob/v6.x/README.md

**Comment by BennyAlex** [comment]
I am using the v6 and the worker file is located under the build folder, not in the main folder

**Comment by wojtekmaj** [comment]
On GitHub, you're viewing the most recent, unreleased code. If you look for README on the most recent released version, head to npmjs.com.

**Comment by BennyAlex** [comment]
okay you are right, but the text here is a bit confusing

> React-PDF is under constant development. This documentation is written for React-PDF 6.x branch. If you want to see documentation for other versions of React-PDF, use dropdown on top of GitHub page to switch to an appropriate tag.

And also the v6 link is broken. 

Thanks for your help :)

**Comment by wojtekmaj** [comment]
Oh, thanks for the heads up, that's definitely something I should fix :D

**Pull request closed without merging**
