### PR TITLE
Pin pdfjs-dist to 2.0.305

### LINKED ISSUE #149: `entry.noworker` doesn't work because of `pdfjs-dist` update
Since the version [v2.0.310](https://github.com/mozilla/pdfjs-dist/tree/v2.0.310/build), the file `pdf.combined.js` in not present in the build anymore. Hence, the `entry.noworker` doesn't work.

They removed this entry in [this PR](https://github.com/mozilla/pdf.js/pull/9385).
I don't understand why but as a temporary solution to get this lib working you can pin the dependency of `pdfjs-dist` to `2.0.305`.

### PR DESCRIPTION
**Pull request by Kerumen**
Fixes #149

As a side note, you have both `package-lock.json` and `yarn.lock`. This is confusing. Chose one of them and remove the other.

### CODE REVIEW

**Comment by wojtekmaj** [comment]
Hey @Kerumen,
thanks so much for this PR. I'll make sure to make a new release soon, but I'm travelling so that might take a little longer.

Hmm. I was hoping that providing package-lock.json and yarn.lock I'd help the users of both package managers having desirable experience by having versions locked. Was I wrong?

**Comment by Kerumen** [comment]
@wojtekmaj It can help but then you have to maintain 2 lockfiles which is annoying (and confusing). I updated a dependency, I have to run both `npm` and `yarn` to get their respective lockfiles updated. If you contribute to a project with a `yarn.lock`, you'll use `yarn`, if you contribute to a project which uses `npm`, you'll use `npm`. I guess that's simpler.

Do you have any collaborators on this lib or are you alone? You should add at least one, it will help when you are MIA for some reasons :)

**Comment by wojtekmaj** [comment]
Used to have a collaborator (the original author of this project) but sadly they [no longer contribute](https://www.youtube.com/watch?v=deo8xhff3bI) :(

**Comment by Kerumen** [comment]
I can propose myself if you want to have some backup :)

**Comment by wojtekmaj** [comment]
That would be awesome! Welcome to the "team" ;)

**Pull request merged**
