### PR TITLE
Upgrade pdfjs-dist to 2.4.456

### PR DESCRIPTION
**Pull request by kylemellander**
https://github.com/wojtekmaj/react-pdf/issues/280

Due to issues caused with cross site loading of the pdf service worker, it is needed for us to upgrade the version of the `pdfjs-dist` package.    

There was one deprecation that was raised in this upgrade that is addressed regarding the EventBus.  The default global event bus was deprecated, so you have to manually manage it.

### CODE REVIEW

**Comment by kylemellander** [comment]
I'm still working on getting the build/test going, but wanted to put this out there to start the work/collaboration on this

**Comment by kylemellander** [comment]
I haven't tested all the different usages, but the ones I have tested, this works 👍.

**Comment by wojtekmaj** [comment]
Hi,
thanks for this PR. Unfortunately, the newest stable PDF.js is 2.3.200 at the moment, so while your changes will certainly make it easier for me to do the upgrade, which I'm thankful for, I can't merge it right now.

**Comment by wojtekmaj** [comment]
Hi! 2.4.456 is marked as stable, so I'm gonna go ahead and upgrade pdfjs-dist.

Two questions:

* There doesn't seem to be any warning, error or a failing test if no EventBus is provided. Is there something we're missing and should be tested either manually or automatically?
* Why entry points for Jest had to be changed?

**Comment by kylemellander** [comment]
@wojtekmaj Great news! 

To answer your questions:

- That seems like a good thing to add.  I'll try to find some time to add that in.
- I explained in the [commit to make the change](https://github.com/wojtekmaj/react-pdf/pull/550/commits/7cc9a94516784f894845c25ad1ed7d8cec03723e).  It says: 

> The ES6 version requires support of ReadableStream causing issues.  
Rather than using a polyfill or mocking this, we should just assume that 
it has been compiled to a working syntax, which for the tests is ES5.

**Comment by wojtekmaj** [comment]
Thanks for your answers! 

It seems like indeed the ES6 version of pdfjs-dist does not use ReadableStream anymore. It used to work fine. So, we can't use ES6 version by default just yet, because it's a breaking change. Not something you would expect when jumping from 2.3 to 24, but Mozilla can't really use semver, unfortunately.

Based on the insight you kindly shared, I've decided to raise [another PR](https://github.com/wojtekmaj/react-pdf/pull/583) upgrading pdfjs-dist to 2.4.456, **but** keeping ES5 version for **ALL** entry files to avoid potential compatibility issues. I added you as a co-author there - hope you don't mind me crediting you this way.

**Pull request closed without merging**
