### PR TITLE
Implement canvasRef in Page and PageCanvas components

### LINKED ISSUE #666: Expose page canvas ref
**Before you start - checklist**

 - [x] I understand that React-PDF does not aim to be a fully-fledged PDF viewer and is only a tool to make one
 - [x] I have checked if this feature request is not already reported

**Is your feature request related to a problem? Please describe.**

Currently, there's no convenient way to access the internal canvas ref on the `Page` element – even though this would be extremely helpful for rendering additional content on top of the PDF that is loaded and is scrollable at the same time.

Quick example – imagine you've developed a machine learning pipeline that extracts the text of a document (OCR, NLP, etc), then runs a model to highlight relevant clauses of a legal document for review. We can use this library to render the PDF quickly and efficiently, but it's inconvenient to superimpose bounding boxes for these highlights on the PDF without direct access to the existing canvas element.

**Describe the solution you'd like**

The `Page` element supports both a `ref` and an additional `inputRef` for the `<div>` *around* the `<canvas>` element. I propose adding a third property, `canvasRef`, so that applications can render additional content on top of the PDF without needing to worry about scroll performance / syncing, conflicting mouse events, etc.

**Describe alternatives you've considered**

We work around this by creating a new, second `<canvas>` element that sits on top of the existing one and rendering application content there, but this is inconvenient and less performant.

### PR DESCRIPTION
**Pull request by wojtekmaj**
Closes #666 😈

### CODE REVIEW

**Comment by wojtekmaj** [comment]
@SamuelMS would you mind grabbing this branch and testing it?

**Comment by SamuelMS** [comment]
@wojtekmaj Yep! Will review in a day or two, thanks for the quick turn-around.

**Comment by AmiralBl3ndic** [comment]
Hello, I am currently working on a project which crucially needs to access and use these components, is this PR still relevant? 🚀😄

**Comment by wojtekmaj** [comment]
Absolutely! It's just waiting for someone to test it out.

**Review by AmiralBl3ndic — APPROVED** [review]

**Comment by AmiralBl3ndic** [comment]
I see nothing potentially problematic here. I'll try it out on a sample project to see if it's working as expected. 👌

**Pull request merged**
