### PR TITLE
chore: use yarn cache

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by wojtekmaj** [comment]
Hello Daniel,
would you please resolve the conflict? It seems like you've used `cache` twice and now we're stuck :)

**Comment by DanielRuf** [comment]
Actually this PR should be merged and used, not the other ;-) Caching with yarn is faster here.
Also the other can be merged if needed but I would evaluate it in a separate PR.

Please do not directly merge PRs =)

**Comment by DanielRuf** [comment]
Updated the PR.

**Comment by wojtekmaj** [comment]
Alright, thank you! ;) That's super interesting stuff!

**Pull request merged**
