### PR TITLE
Bundling problem due to LinkService

### PR DESCRIPTION
**Pull request by jfrolich**
Adding link service from `pdfjs-dist` has the problematic side-effect that it pulls in another full copy of the PDFjs source into the package (it requires back to the root for a small utility function). This is true for all bundlers (I think).

My impression is that the link service is an example of how to implement such a thing. To fix the bundling problem we can do three things as far as I can see:

- Request an update to `pdfjs` and therefore `pdfjs-dist` to fix the problem
- Pull in the code -- with refactoring what is really necessary for the linkService as implemented for react-pdf as a second step.

Not sure what the right solution is. But I already included the minimal sources in the repository for at least a temporary fix of he problem.

### CODE REVIEW

**Comment by jfrolich** [comment]
Hi,

This is not about the worker duplication. I'm not sure this happens for each entry point. But for example the webpack entry point loads `var pdfjs = require('./build/pdf.js');` (the pre build pdfjs). Then when you import `LinkService` in `react-pdf` this also includes the non-pre-build PDFjs in the building (unnecessary). This quick fix reduces the bundle size by 50%. But I agree, probably not the best solution. Which solution do you prefer?

**Comment by jfrolich** [comment]
> If anything is indeed wrong with LinkService, I'd just try and import it directly instead of re-exporting it via our entry file.

I don't know what you are saying here. But I the LinkService is not shipping with PDFjs' library code, but is part of an example viewer. So I guess it's not really supposed to be imported. In PDFjs it's tightly integrated (if I import `Document` I get it and all dependencies).

**Comment by wojtekmaj** [comment]
Ah, you're correct.

Okay, so the problem is that ui_utils.js, sub-dependency of pdf_link_service, imports pdf.js from /lib/pdf.js which then imports tons of different stuff.

This has to be changed on Mozilla's side. Thankfully that should be an easy fix. Stay tuned.

**Comment by jfrolich** [comment]
Yes it's actually `import { createPromiseCapability } from 'pdfjs-lib';` in `web/ui_utils.js` that simply adds a promise decorator (or so), but pulls in all of pdfjs.

**Comment by wojtekmaj** [comment]
Hope you don't mind me closing this - all progress will be tracked in external issue linked above, and I'll mention it in release notes once it gets resolved.

**Comment by jfrolich** [comment]
As pdf.js doesn't seem to resolve this issue anytime soon, how about thinking about a workaround. This really bloats the webpack build. Perhaps a solution would be to put the linkservice in a separate package until this is fixed upstream in PDF.js.

**Comment by jfrolich** [comment]
(I can make a PR for that if you are up for it)

**Comment by wojtekmaj** [comment]
I think it would make sense to fix imports on Mozilla's side. This will benefit everyone who uses the package, not just us, and isn't any harder than fixing it independently.

Mozilla gives away tremendous amount of its work so to contribute is one of the ways to pay them back.

From my experience they are very open to contributions.

**Comment by jfrolich** [comment]
Ah yes, of course. I'll make a pull request there.

**Pull request closed without merging**
