### PR TITLE
WithCredentials only works in options prop

### PR DESCRIPTION
**Pull request by leonschwanitz**
Unfortunately withCredentials only works if you specify it directly in the options prop.

### CODE REVIEW

**Comment by wojtekmaj** [comment]
So you would like to report that specifying it in `file` does not work?

**Comment by leonschwanitz** [comment]
@wojtekmaj Yes we have tested it and it only works in the options prop :)

**Comment by tafelito** [comment]
I'm experiencing the same is indeed an issue. as @leonschwanitz pointed out, `withCredentials` only works when using it  with the options prop. @wojtekmaj is this an issue you're planning on fix?

**Comment by wojtekmaj** [comment]
I don't see any issue, withCredentials is not something that was documented to work anywhere else?

**Pull request closed without merging**
