### PR TITLE
copy source when data is arraybuffer

### PR DESCRIPTION
**Pull request by luocongqiu**
When I pass the Blob file and options params, the Document component will render twice, and the second time source.data will empty

image

### CODE REVIEW

**Comment by wojtekmaj** [comment]
Is there a chance you could add a test that was previously failing, and now isn't, so that we would be sure it doesn't regress?

**Comment by luocongqiu** [comment]
@wojtekmaj  [codesandbox](https://codesandbox.io/s/adoring-dew-67k84l)

**Comment by wojtekmaj** [comment]
Define `options` outside of React function as documentation says and the error is gone.

**Comment by luocongqiu** [comment]
@wojtekmaj In my usage scenario, the options parameter cannot be static, such as password

**Comment by wojtekmaj** [comment]
Use useMemo.

**Pull request closed without merging**
