### PR TITLE
chore: clone last 5 commits

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by DanielRuf** [comment]
By default Travis clones the last 50 commits. Cloning only the last 5 produces faster checkouts and better build times.

**Comment by DanielRuf** [comment]
See https://docs.travis-ci.com/user/customizing-the-build#Git-Clone-Depth

**Comment by wojtekmaj** [comment]
I resolved the conflict in your PR, would you have a look if that's what you intended to add and neither me nor Git messed up? :)

**Comment by DanielRuf** [comment]
LGTM, just these 2 lines are needed.

**Comment by wojtekmaj** [comment]
Now I'm ashamed, your response time is 5 minutes, mine is 10 days :D I'm sorry for the delay. Lots of things happening in personal life, I'm trying to catch up on GitHub :)

Thanks!

**Comment by DanielRuf** [comment]
> Now I'm ashamed, your response time is 5 minutes, mine is 10 days :D I'm sorry for the delay. Lots of things happening in personal life, I'm trying to catch up on GitHub :)

Nothing to be sorry about. Thanks for the feedback and taking care of the conflict. 👍

**Pull request merged**
