### PR TITLE
Update pdfjs-dist to 2.5.207

### LINKED ISSUE #686: Update pdf.js to 2.5.207
**Before you start - checklist**

 - [x] I understand that React-PDF does not aim to be a fully-fledged PDF viewer and is only a tool to make one
 - [x] I have checked if this feature request is not already reported

The latest pdf.js version (2.5.207) contains several performance improvements. Is it possible to update React-PDF to use the latest pdf.js version? Thanks!

### PR DESCRIPTION
**Pull request by wojtekmaj**
Closes #686

### CODE REVIEW

**Comment by wojtekmaj** [comment]
@toszcze Wanna be a beta tester of this one? ;)

**Comment by toszcze** [comment]
@wojtekmaj Sure! :)

**Comment by toszcze** [comment]
@wojtekmaj I'm sorry, but I'm not sure how I can install this version using npm. I've tried `npm i git+ssh://git@github.com:wojtekmaj/react-pdf.git#pdfjs-dist-2.5.207`, but it failed (`Couldn't find the node_modules state file - running an install might help`).

**Comment by toszcze** [comment]
@wojtekmaj I built the module locally, linked it into my project, but I'm getting the following message when I try to build my project:
```
ERROR in ../react-pdf/dist/esm/entry.webpack.js
Module build failed (from ./node_modules/eslint-loader/index.js):
Error: Cannot find module 'eslint-config-wojtekmaj/react'
Referenced from: /../projekty/react-pdf/.eslintrc.json
```

**Comment by wojtekmaj** [comment]
I released this PR as 5.1.0-beta. You can use `npm install react-pdf@next` or `yarn add react-pdf@next` to try it out.

**Comment by toszcze** [comment]
@wojtekmaj It works for me.

**Pull request merged**
