### PR TITLE
simplifies code contributions & automates the dev setup.

### PR DESCRIPTION
**Pull request by nisarhassan12**
Hi! there :slightly_smiling_face:

This PR simplifies code contributions by fully automating the setup with Gitpod (a free online VS Code-like IDE).

With a single click, it'll launch a workspace and automatically:

- clone the react-pdf repo.
- install the dependencies.
- run `yarn build` and `yarn test`.

So that anyone interested in contributing can start straight away.

You can give it a try on My Fork of the repo via the following link:

https://gitpod.io/#https://github.com/nisarhassan12/react-pdf

image

### CODE REVIEW

**Comment by nisarhassan12** [comment]
Rebase on top of the latest master @wojtekmaj

**Comment by wojtekmaj** [comment]
After giving it some thought I don't think this would be a worthy addition. 

This tool doesn't get much traction so it wouldn't be helpful to lots of users (GitHub Workspaces is [much more popular](https://trends.google.com/trends/explore?q=gitpod,github%20workspaces) while still quite exotic).

And the commands we use to install are just... very standard. All it could take for Gitpod to automatically install everything is to look which package manager is used and run either `npm i` or `yarn install`, that's all. That sounds like a much easier thing to achieve than pushing .gitpod.yml to 100s of thousands of repos out there.

**Comment by jankeromnes** [comment]
Thanks for the honest feedback @wojtekmaj! 🙌

I totally get that `yarn install && yarn build` is straightforward, and probably doesn't warrant automation.

> This tool doesn't get much traction so it wouldn't be helpful to lots of users (GitHub Workspaces is [much more popular](https://trends.google.com/trends/explore?q=gitpod,github%20workspaces) while still quite exotic).

Well, Gitpod gets some traction with over 300K developers & businesses already using it. It's also [open source](https://github.com/gitpod-io/gitpod/) and actually usable today.

Checking the link you provided, I think it's the other way around (Gitpod is the blue line):

gitpod-vs-github-workspaces

(However, I know you meant GitHub Codespaces, where it's a bit closer, but blue is still higher on average.)

**Comment by wojtekmaj** [comment]
> I think it's the other way around (Gitpod is the blue line)

🤦 I'm a complete idiot. Sorry about that!

**Pull request closed without merging**
