### PR TITLE
Update pdfjs-dist to 2.4.456

### PR DESCRIPTION
**Pull request by wojtekmaj**

### CODE REVIEW

**Comment by GabrielF9** [comment]
@wojtekmaj How can I update my React App with the changes to this PR?

**Comment by wojtekmaj** [comment]
You don't need to do anything if you're already on the beta. React-PDF follows semver.

This change will be released soon either the next React-PDF 5 beta.

**Comment by GabrielF9** [comment]
Oh yes, right. Do you have a forecast for when the stable version of React PDF 5 comes out?

**Comment by wojtekmaj** [comment]
I think we could do this late this week. Seems stable enough for me.

**Pull request merged**
