### PR TITLE
Allow overriding of inline styles on canvas element

### PR DESCRIPTION
**Pull request by maxlew**
Just a small change to allow passing a canvasStyle object to Page. Get's passed through to PageCanvas and ends up on the `<canvas>` element. 

Can help with handling weird responsive layouts.

### CODE REVIEW

**Comment by maxlew** [comment]
Unrelated but looks like the builds failing as upath doesn't like node10. Just need to update webpack which updates watchpack, which updates chokidar, which has been updated to use upath 1.0.5 which no longer has `>=4 <=9` in it's node requirements 😅

**Comment by wojtekmaj** [comment]
Regarding build failing issue, I think for now I'll have to keep Node 9.x for builds as we can't really update Webpack - it is dependency of pdfjs-dist :(

**Comment by wojtekmaj** [comment]
@maxlew could you kindly merge upstream/master to your branch? CI builds are fixed there and I'd like to make sure we're not merging something that will break the build. Thank you! 🙇

**Comment by maxlew** [comment]
@wojtekmaj I've merged in master from upstream and fixed an issue with the tests. 

With preparing a style object so it's not comparing to a new reference each time. If we did a deep compare in PageCanvas we'd have to move away from PureComponent, not sure if that'd be negative performance for the majority of use cases. However I can't find something that simply explains how to prepare an object so react isn't comparing new references each time. I'll keep looking though.

**Comment by mrogach2350** [comment]
@wojtekmaj Will this be merged in soon? I'm having issues getting the text layer to line up with the canvas and would like to be able to pass it style props to maintain layers line up if window size changes. Unless there is another solution to that problem of course. Currently using `v4.0.31`

**Comment by Carlosf96** [comment]
Hello,
I'm in need to use styles aswell , i'm attempting , to resize it so it will be a super small square so that it can be used as a sort of small thumbnail, or maybe I am taking the wrong approach anyways this would also be nice for others who are needing to pass styles.

Thanks.

**Review by aek-pokittisak — APPROVED** [review]

**Pull request closed without merging**
