### PR TITLE
Add IDs to span elements created by TextLayerItem component

### PR DESCRIPTION
**Pull request by jedhelmers**
1. Adding an ID to the pdf's spans. Something to grab onto for annotation purposes.

### CODE REVIEW

**Comment by jedhelmers** [comment]
I'd like to build annotation's but I need the span tags to have indices on them.

**Comment by wojtekmaj** [comment]
We can't do this. If there are multiple pages or multiple documents, we're going to end up with duplicated IDs which is not a valid HTML practice. We could add data-pageNumber and data-textLayerItemIndex.

**Comment by jedhelmers** [comment]
Boogers. I could add a document-level unique id that passes down into TextLayerItem and I can throw the page number in as well. That should take care of it

**Comment by wojtekmaj** [comment]
I think data attributes are the best approach :)

**Review by mrbaguvix — CHANGES_REQUESTED** [review]
Lots of things have changed please merge **master** into **your** branch.

**Pull request closed without merging**
