### PR TITLE
Explicitly initialize an EventBus instance

### PR DESCRIPTION
**Pull request by danieltott**
Work taken directly from #550 by @kylemellander 

Included in [pdf.js v2.4.456](https://github.com/mozilla/pdf.js/releases/tag/v2.4.456) was a deprecation for `getGlobalEventBus` which was being implicitly used behind the scenes. They now suggest the following:

> explicitly initialize an EventBus instance, and provide that when initializing the relevant viewer components.

More info on that here: [Deprecate `getGlobalEventBus` and update the "viewer components" examples accordingly](https://github.com/mozilla/pdf.js/pull/11631)

### CODE REVIEW

**Comment by wojtekmaj** [comment]
Can you check "Allow edits from maintainers" please?

**Comment by danieltott** [comment]
@wojtekmaj Trying to figure out how to do that - the checkbox that is supposed to be in the sidebar is not there - have no idea what's going on with that. Should I add you as a collaborator? Or close this one and try a new PR and see if it shows up if I try again?

**Comment by danieltott** [comment]
Turns out forking it under the Sprokets org prevents that checkbox from being enabled: https://github.community/t/how-can-we-enable-allow-edits-from-maintainers-by-default/2847

I added you with write access to the repo - if that isn't sufficient I can re-fork it on my personal account and create a new PR.

**Comment by wojtekmaj** [comment]
Hmmm, that didn't do it - I raised another PR with your changes, no need to worry :)

**Pull request closed without merging**
